(function(g){var window=this;var FDa=function(a,b){return g.fc(a,b)},c6=function(a){g.nn(a,"zx",g.Fb());
return a},d6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.qn(a.o,b,c)},GDa=function(a,b){var c=[];
g.Zk(b,function(a){try{var b=g.OD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.ND(b)&&c.push(a):c.push(a)},a);
return c},HDa=function(a,b){var c=GDa(a,b);
(0,g.C)(c,function(a){g.OD.prototype.remove.call(this,a)},a)},IDa=function(a){if(a.Ld){if(a.Ld.locationOverrideToken)return{locationOverrideToken:a.Ld.locationOverrideToken};
if(null!=a.Ld.latitudeE7&&null!=a.Ld.longitudeE7)return{latitudeE7:a.Ld.latitudeE7,longitudeE7:a.Ld.longitudeE7}}return null},JDa=function(a,b,c,d){var e=new g.dn(null,void 0);
a&&g.en(e,a);b&&g.fn(e,b);c&&g.gn(e,c);d&&g.hn(e,d);return e},e6=function(a,b){g.GE[a]=!0;
var c=g.EE();c&&c.publish.apply(c,arguments);g.GE[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Ym;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",KDa(this,a.capabilities||""),LDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},KDa=function(a,b){a.capabilities.clear();
(0,g.ge)(b.split(","),g.La(FDa,MDa)).forEach(function(b){a.capabilities.add(b)})},LDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},NDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},ODa=function(a){return new g6(a)},PDa=function(a){return g.Fa(a)?(0,g.I)(a,ODa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Fa(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},QDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.Ra(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.Ra(a,function(a){return h6(a,b)})},RDa=function(){var a=(0,g.QH)();
a&&HDa(a,a.o.ce(!0))},n6=function(){var a=g.TH("yt-remote-connected-devices")||[];
g.qb(a);return a},SDa=function(a){if(g.Wa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},TDa=function(a){g.SH("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.TH("yt-remote-device-id");a||(a=k6(),g.SH("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Va(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Va(a,b);g.VH()&&g.sb(a,b);a=SDa(a);if(g.Wa(a))try{g.pH("remote_sid")}catch(c){}else try{g.oH("remote_sid",a.join(","),-1)}catch(c){}},UDa=function(){return g.TH("yt-remote-session-browser-channel")},VDa=function(){return g.TH("yt-remote-local-screens")||[]},WDa=function(){g.SH("yt-remote-lounge-token-expiration",!0,86400)},XDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(VDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Mm)(c,function(a){return!g.Va(b,a)})&&WDa();
g.SH("yt-remote-local-screens",a,31536E3)},YDa=function(a,b){g.SH("yt-remote-session-browser-channel",a);
g.SH("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Va(c,d)||c.push(d);TDa(c);q6()},r6=function(a){a||(g.UH("yt-remote-session-screen-id"),g.UH("yt-remote-session-video-id"));
q6();a=n6();g.$a(a,p6());TDa(a)},ZDa=function(){if(!s6){var a=g.ZD();
a&&(s6=new g.ID(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},$Da=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?aEa(a.shift(),function(){u6(a)}):v6()},bEa=function(a){return"chrome-extension://"+a+w6},aEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=$Da();
a&&a(!1,"No cast extension found")},dEa=function(){if(cEa){var a=2,b=$Da(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;aEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},eEa=function(){dEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Ed=b;this.D=(0,g.A)(this.WK,this);this.o=!1;this.A=0;this.B=this.Ia=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.un(this);this.A=new g.Ig;this.A.setInterval(250)},gEa=function(a,b,c){a.Tj=1;
a.Dh=c6(b.clone());a.hj=c;a.D=!0;fEa(a,null)},A6=function(a,b,c,d,e){a.Tj=1;
a.Dh=c6(b.clone());a.hj=null;a.D=c;e&&(a.EF=!1);fEa(a,d)},fEa=function(a,b){a.Qk=(0,g.H)();
B6(a);a.di=a.Dh.clone();d6(a.di,"t",a.F);a.Rn=0;a.Xc=a.o.Lt(a.o.In()?b:null);0<a.tu&&(a.Qq=new g.Hl((0,g.A)(a.SG,a,a.Xc),a.tu));a.Y.X(a.Xc,"readystatechange",a.dV);var c=a.Ji?g.nc(a.Ji):{};a.hj?(a.Qr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.di,a.Qr,a.hj,c)):(a.Qr="GET",a.EF&&!g.Vd&&(c.Connection="close"),a.Xc.send(a.di,a.Qr,null,c));a.o.Bf(1)},jEa=function(a,b,c){for(var d=!0;!a.ri&&a.Rn<c.length;){var e=hEa(a,c);
if(e==C6){4==b&&(a.Eh=4,D6(15),d=!1);break}else if(e==iEa){a.Eh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Eh=1,D6(17),d=!1);a.Hf=a.Hf&&d;d||(F6(a),G6(a))},hEa=function(a,b){var c=a.Rn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return iEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Rn=d+c;return e},lEa=function(a,b){a.Qk=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.di=a.Dh.clone();g.nn(a.di,"DOMAIN",c);g.nn(a.di,"t",a.F);try{a.Jf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Eh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in kEa)k=H6[l]=kEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.yd(g.Mc("b/12014412"),d+"</body></html>");a.Jf.open();a.Jf.write(g.md(c));a.Jf.close();a.Jf.parentWindow.m=(0,g.A)(a.jU,a);a.Jf.parentWindow.d=(0,g.A)(a.PE,a,!0);a.Jf.parentWindow.rpcClose=(0,g.A)(a.PE,a,!1);c=a.Jf.createElement("DIV");a.Jf.parentWindow.document.body.appendChild(c);d=g.$c(a.di.toString());d=g.zb(g.Xc(d));d=g.yd(g.Mc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.sd(c,g.md(d));a.o.Bf(1)},B6=function(a){a.hy=(0,g.H)()+
a.C;
mEa(a,a.C)},mEa=function(a,b){if(null!=a.ql)throw Error("WatchDog timer not null");
a.ql=I6((0,g.A)(a.yU,a),b)},J6=function(a){a.ql&&(g.v.clearTimeout(a.ql),a.ql=null)},G6=function(a){a.o.xB()||a.ri||a.o.zq(a)},F6=function(a){J6(a);
g.uf(a.Qq);a.Qq=null;a.A.stop();g.An(a.Y);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Jf&&(a.Jf=null)},E6=function(a,b){try{a.o.IE(a,b),a.o.Bf(4)}catch(c){}},oEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;nEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){oEa(a,b,c,d,f)},f)})}},nEa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},pEa=function(a){this.o=a;
this.A=new y6},qEa=function(a){var b=L6(a.o,a.Gl,"/mail/images/cleardot.gif");
c6(b);oEa(b.toString(),5E3,(0,g.A)(a.YJ,a),3,2E3);a.Bf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Ge=new z6(a,void 0,void 0,void 0),a.Ge.Ji=a.qu,b=a.o,b=L6(b,b.In()?a.zm:null,a.ru),D6(5),!g.Td||g.Ec(10))d6(b,"TYPE","xmlhttp"),A6(a.Ge,b,!1,a.zm,!1);else{d6(b,"TYPE","html");var c=a.Ge;a=!!a.zm;c.Tj=3;c.Dh=c6(b.clone());lEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},rEa=function(a,b){this.o=a;
this.map=b;this.context=null},sEa=function(a){g.wf.call(this,"statevent",a)},tEa=function(a,b){g.wf.call(this,"timingevent",a);
this.size=b},uEa=function(a){g.wf.call(this,"serverreachability",a)},xEa=function(a){vEa(a);
if(3==a.o){var b=a.nn++,c=a.Zo.clone();g.nn(c,"SID",a.B);g.nn(c,"RID",b);g.nn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.Tj=2;b.Dh=c6(c.clone());(new Image).src=b.Dh;b.Qk=(0,g.H)();B6(b)}wEa(a)},yEa=function(a){a.vK(1,0);
a.Zo=L6(a,null,a.pu);Q6(a)},vEa=function(a){a.rh&&(a.rh.abort(),a.rh=null);
a.zc&&(a.zc.cancel(),a.zc=null);a.Fg&&(g.v.clearTimeout(a.Fg),a.Fg=null);R6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.xh&&(g.v.clearTimeout(a.xh),a.xh=null)},zEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new rEa(a.WP++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ie||a.xh||(a.xh=I6((0,g.A)(a.OE,a),0),a.Kj=0)},BEa=function(a,b){if(1==a.o){if(!b){a.nn=Math.floor(1E5*Math.random());
var c=a.nn++,d=new z6(a,"",c,void 0);d.Ji=null;var e=S6(a),f=a.Zo.clone();g.nn(f,"RID",c);g.nn(f,"CVER","1");P6(a,f);gEa(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?AEa(a,b):0==a.A.length||a.ie||AEa(a))},AEa=function(a,b){if(b)if(6<a.wi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.nn-1;var d=S6(a)}else c=b.G,d=b.hj;else c=a.nn++,d=S6(a);var e=a.Zo.clone();g.nn(e,"SID",a.B);g.nn(e,"RID",c);g.nn(e,"AID",a.nk);P6(a,e);c=new z6(a,a.B,c,a.Kj+1);c.Ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;gEa(c,e,d)},P6=function(a,b){if(a.Dd){var c=a.Dd.cB();
c&&g.Sb(c,function(a,c){g.nn(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.wi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.wi?e:f-d;try{g.Sb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},CEa=function(a){a.zc||a.Fg||(a.G=1,a.Fg=I6((0,g.A)(a.NE,a),0),a.Cj=0)},T6=function(a){if(a.zc||a.Fg||3<=a.Cj)return!1;
a.G++;a.Fg=I6((0,g.A)(a.NE,a),DEa(a,a.Cj));a.Cj++;return!0},M6=function(a,b,c){a.Nr=c;
a.Uf=b.Tg;a.F||yEa(a)},R6=function(a){null!=a.yi&&(g.v.clearTimeout(a.yi),a.yi=null)},DEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Dd&&(c=null);var d=(0,g.A)(a.WV,a);c||(c=new g.dn("//www.google.com/images/cleardot.gif"),c6(c));nEa(c.toString(),1E4,d)}else D6(2);EEa(a,b)},EEa=function(a,b){a.o=0;
a.Dd&&a.Dd.bA(b);wEa(a);vEa(a)},wEa=function(a){a.o=0;
a.Uf=-1;if(a.Dd)if(0==a.C.length&&0==a.A.length)a.Dd.wt();else{g.db(a.C);var b=g.db(a.A);a.C.length=0;a.A.length=0;a.Dd.wt(b)}},L6=function(a,b,c){var d=g.on(c);
if(""!=d.A)b&&g.fn(d,b+"."+d.A),g.gn(d,d.D);else{var e=window.location;d=JDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Wl&&g.Sb(a.Wl,function(a,b){g.nn(d,b,a)});
g.nn(d,"VER",a.wi);P6(a,d);return d},I6=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new sEa(V6,a))},FEa=function(){},GEa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.J.call(this);
this.o=new g.U(this.ZT,0,this);g.K(this,this.o);this.Ed=5E3;this.A=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.HD;this.A=new W6(this.zW,this);this.o=this.kb=null;this.Bb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},HEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Nr,sessionId:a.o.B,arrayId:a.o.nk}},IEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&BEa(a.o),xEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},JEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Qb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.fh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Id:g.La(a.D,e)};c&&(a.Rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.mF(b,a)},NEa=function(){var a=KEa;
LEa();b7.push(a);MEa(b7)},c7=function(a,b){LEa();
var c=b7,d=OEa(a,String(b));g.Wa(c)?PEa(d):(MEa(c),(0,g.C)(c,function(a){a(d)}))},LEa=function(){b7||(b7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",b7,void 0))},PEa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},MEa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},OEa=function(a,b){var c=((0,g.H)()-QEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.V.call(this);
this.G=a;this.o=[]},REa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},SEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ge)(a.o,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=REa(a,b[d])||c;return c},TEa=function(a,b){var c=a.o.length;
a.o=(0,g.ge)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ia=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},UEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.kL,a),(0,g.A)(a.jL,a))}},i7=function(a){var b=PDa(VDa());
b=(0,g.ge)(b,function(a){return!a.uuid});
return SEa(a,b)},k7=function(a,b){XDa((0,g.I)(a.o,NDa));
b&&WDa()},m7=function(a,b){g.V.call(this);
this.F=b;var c=g.TH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Va(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;l7("Initialized with "+g.Og(this.o))},VEa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Xb(b)!=g.Xb(a.o))var c=!1;
else{c=g.cc(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Og(a.o)),a.o=b,a.V("screenChange"));WEa(a)},o7=function(a){isNaN(a.B)||g.DE(a.B);
a.B=g.BE((0,g.A)(a.ax,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},XEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},WEa=function(a){a=g.cc(g.Tb(a.o,function(a){return a}));
g.qb(a);a.length?g.SH("yt-remote-online-screen-ids",a.join(","),60):g.UH("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};YEa(this)},$Ea=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ae();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);VEa(a.A,l,function(a){e(a?l:null)})}else c?ZEa(a,c,(0,g.A)(function(a){var f=q7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));VEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},aFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},ZEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.mF($6(a.F,"/pairing/get_lounge_token_batch"),e)},bFa=function(a){a.o=a.B.Ae();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},YEa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.xL,a));bFa(a);a.C=PDa(g.TH("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.C));a.A=new m7(a.F,(0,g.A)(a.Ae,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.SH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,NDa)));r7(a);a.D[b.uuid]=b.id;g.SH("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.TH("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.V.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.R,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.GW,this);this.D=(0,g.A)(this.KU,this);this.C=g.BE((0,g.A)(function(){cFa(this,null)},this),12E4)},dFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Og(b))},cFa=function(a,b){g.DE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Aq,a),d=(0,g.A)(a.Fe,a);a.nB(b,c,d,5)}}else a.Fe(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.JW,this);this.o=g.z},eFa=function(a){a.o=a.J.WG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Aq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.Fe(a)},a))},fFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}ZDa()&&(b.env_useStageMdx=1);return g.dh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.BE((0,g.A)(this.qk,this,null),150)},x7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.iT,this)},gFa=function(a,b){return b?g.Ra(a.B,function(a){return h6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},KEa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.uf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.LE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.qk(null)):a.V("yt-remote-cast2-session-change",null))},hFa=function(a){var b=a.A.VG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=gFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},nFa=function(a,b,c,d,e,f,k){iFa()?jFa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?kFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?kFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.UH("yt-remote-cast-available"),g.UH("yt-remote-cast-receiver"),lFa(),c(!1))},d?g.OE("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?eEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(dEa(),u6(mFa.map(bEa))))):B7("Cannot initialize because not running Chrome")},lFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);oFa(!1);g.JE(G7);G7.length=0},H7=function(){return!!g.TH("yt-remote-cast-installed")},pFa=function(){var a=g.TH("yt-remote-cast-receiver");
return a?a.friendlyName:null},qFa=function(){B7("clearCurrentReceiver");
g.UH("yt-remote-cast-receiver")},rFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.IE("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},iFa=function(){var a=0<=g.Qb.search(/ (CrMo|Chrome|CriOS)\//);
return g.qL||a},sFa=function(a,b){F7().init(a,b)},jFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.SH("yt-remote-cast-available",a);e6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.SH("yt-remote-cast-receiver",a);e6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.SH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+i6(a));
a||g.UH("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},kFa=function(a,b){E7(!0);
C7(!1);sFa(a,function(a){a?(oFa(!0),g.LE("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.UH("yt-remote-cast-available"),g.UH("yt-remote-cast-receiver"),lFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.SH("yt-remote-cast-installed",a)},I7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},oFa=function(a){B7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Yf=!1;this.J=this.H=this.A=this.C=0;this.B=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Yf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.oc(a.o);b.hasPrevious=a.Yf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.YC;this.B=this.A=null;this.J=(0,g.A)(this.HQ,this);this.G=(0,g.A)(this.tn,this);this.H=(0,g.A)(this.GQ,this);this.K=(0,g.A)(this.TQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ry,this),tFa(this))):c=3;0!=c&&(b?this.ry(c):g.BE((0,g.A)(function(){this.ry(c)},this),0));
var d=rFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},tFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.dT,a),this))},a)},uFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Lc()&&g.$C(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){uFa(a);
a.C.setPlayerContextData(R7(b));tFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.tn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.tn(a.B.media[0]))},vFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.ob=this.o=null;this.sa=a;this.T.push(g.oG(window,"beforeunload",(0,g.A)(this.aL,this)));this.A=[];this.ob=new L7;this.aa=b.id;this.o=wFa(this,c);this.o.subscribe("handlerOpened",this.LQ,this);this.o.subscribe("handlerClosed",this.IQ,this);this.o.subscribe("handlerError",this.JQ,this);this.o.subscribe("handlerMessage",this.KQ,this);JEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.ob.videoId;
g.VH()&&g.SH("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},wFa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},xFa=function(a){a.D=g.BE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.DE(a.D);
a.D=NaN},d8=function(a){g.DE(a.R);
a.R=NaN},yFa=function(a){e8(a);
a.L=g.BE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.DE(a.L);
a.L=NaN},AFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.ob.reset(),b8(a,1),f8(a,"getNowPlaying"),zFa(a)):a.F(1)},BFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ob.videoId&&(g.ic(b.params)?a.ob.o=null:a.ob.o=b.params,a.V("remotePlayerChange"))},CFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ob.listId=b.params.listId||a.ob.listId;Q7(a.ob,c,d);a.V("remoteQueueChange")},EFa=function(a,b){b.params=b.params||{};
CFa(a,b);DFa(a,b);a.V("autoplayDismissed")},DFa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.ob,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ob.playerState&&(c=-1E3);a.ob.playerState=c;c=Number(b.params.loadedTime);a.ob.J=isNaN(c)?0:c;c=Number(b.params.duration);a.ob.H=isNaN(c)?0:c;c=a.ob;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=isNaN(d)?!1:!0;c=a.ob;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.ob.playerState?yFa(a):e8(a);a.V("remotePlayerChange")},FFa=function(a,b){if(-1E3!=
a.ob.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ob.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.ob,isNaN(c)?0:c);a.V("remotePlayerChange")}},GFa=function(a,b){var c="true"==b.params.muted;
a.ob.volume=parseInt(b.params.volume,10);a.ob.muted=c;a.V("remotePlayerChange")},HFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},IFa=function(a,b){var c="true"==b.params.hasNext;
a.ob.Yf="true"==b.params.hasPrevious;a.ob.hasNext=c;a.V("previousNextChange")},zFa=function(a){g.DE(a.K);
a.K=g.BE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Og(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.md=a;this.A=[];this.A.push(this.md.$_s("screenChange",(0,g.A)(this.EW,this)));this.A.push(this.md.$_s("onlineScreenChange",(0,g.A)(this.CS,this)))},NFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.tE("MDX_CONFIG")||b;RDa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),ZDa()&&(h8.o="/api/loungedev"));i8||(i8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));JFa();var c=j8();if(!c){var d=new p7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);nFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Og(b)),m8.push(g.IE("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.IE("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.IE("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.IE("yt-remote-cast2-session-change",KFa)),m8.push(g.IE("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),qFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.WE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Og(a)),LFa(a),c.start(),k8()||MFa())},PFa=function(){var a=OFa();
H7()&&g.TH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},OFa=function(){var a=j8().md.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return QDa(a)},s8=function(){var a=QFa();
!a&&H7()&&pFa()&&(a={key:"cast-selector-receiver",name:pFa()});return a},QFa=function(){var a=OFa(),b=q8();
b||(b=o8());return g.Ra(a,function(a){return b&&h6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().Ae();return m6(b,a)},KFa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.x("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.x("yt.mdx.remote.currentScreenId_")},RFa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},SFa=function(){return g.x("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.x("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||RFa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.VH();
if(!a)return null;var b=j8().Ae();return m6(b,a)},u8=function(a,b){q8()&&q8();
RFa(a.id);var c=new $7(h8,a,p8());c.connect(b,SFa());c.subscribe("beforeDisconnect",function(a){e6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},MFa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),qFa(),l8("Skipping connecting because no session screen found."))},JFa=function(){var a=p8();
if(g.ic(a)){a=p6();var b=g.TH("yt-remote-session-name")||"",c=g.TH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},LFa=function(a){a?(g.SH("yt-remote-session-app",a.app),g.SH("yt-remote-session-name",a.name)):(g.UH("yt-remote-session-app"),g.UH("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.B=new g.DG(this);g.K(this,this.B);this.B.O(b,"onCaptionsTrackListChanged",this.WR);this.B.O(b,"captionschanged",this.FQ);this.B.O(b,"captionssettingschanged",this.lG);this.B.O(b,"videoplayerreset",this.Bq);this.B.O(b,"mdxautoplaycancel",this.XJ);this.T=this.B.O(b,"onVolumeChange",this.sE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.HE,this);c.subscribe("remotePlayerChange",this.wn,this);c.subscribe("remoteQueueChange",this.Bq,this);c.subscribe("autoplayUpNext",this.eE,
this);c.subscribe("previousNextChange",this.EE,this);c.subscribe("nowAutoplaying",this.wE,this);c.subscribe("autoplayDismissed",this.dE,this);this.suggestion=null;this.J=new g.HQ(64);this.C=new g.U(this.iG,500,this);g.K(this,this.C);this.F=new g.U(this.jG,1E3,this);g.K(this,this.F);this.L=new x6(this.gW,0,this);g.K(this,this.L);this.G={};this.R=new g.U(this.JG,1E3,this);g.K(this,this.R);this.K=new g.Hl(this.zO,1E3,this);g.K(this,this.K);this.N=g.z;this.lG();this.Bq();this.wn()},z8=function(a,b){a.D.Ke(b,
a.A.getVideoData().lengthSeconds)},TFa=function(a){z8(a,0);
a.C.stop();A8(a,new g.HQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.qc(c,b));a.o.WF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.ze();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.ek,IDa(c));A8(a,new g.HQ(1))},UFa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{D4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.NQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.RU(a.A,d);a.J=b;VFa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.ksa()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.IV(this,250);g.K(this,this.B);this.C=a;this.O(a,"presentingplayerstatechange",this.D);WFa(this,g.NU(a))},WFa=function(a,b){if(3==a.C.getPresentingPlayerType()){var c={RECEIVER_NAME:a.C.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.AV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.AV("Playing on $RECEIVER_NAME",c):g.AV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.ZW.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.O(a,"onMdxReceiversChange",this.L);this.O(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.kV.call(this,a);
this.A={key:k6(),name:"This computer"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.cn=new g.HQ(64);this.J=0;this.H=-1;if(!g.pN(g.Y(this.player))){a=this.player;var b=g.wQ(a);b&&(b=b.fn())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.bV(a,b.element,4)}},VFa=function(a,b,c){a.cn=c;
a.player.V("presentingplayerstatechange",new g.SQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ga(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ek,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=IDa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().Ae(),(d=m6(d,b.key))&&u8(d,1))}},kEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},XFa={},MDa={cY:"atp",H2:"ska",V1:"que",f1:"mus",D2:"sus",o_:"dsp",n2:"seq"};
f6.prototype.sh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",cEa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),mFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.J);g.h=x6.prototype;g.h.VK=function(a){this.C=arguments;this.o=!1;this.Ia?this.B=(0,g.H)()+this.Ed:this.Ia=g.Jg(this.D,this.Ed)};
g.h.stop=function(){this.Ia&&(g.Kg(this.Ia),this.Ia=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();x6.ga.W.call(this)};
g.h.WK=function(){this.B?(this.Ia=g.Jg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ia=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Ji=null;g.h.Hf=!1;g.h.ql=null;g.h.hy=null;g.h.Qk=null;g.h.Tj=null;g.h.Dh=null;g.h.di=null;g.h.hj=null;g.h.Xc=null;g.h.Rn=0;g.h.Jf=null;g.h.Qr=null;g.h.Eh=null;g.h.Am=-1;g.h.EF=!0;g.h.ri=!1;g.h.tu=0;g.h.Qq=null;var iEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.dV=function(a){a=a.target;var b=this.Qq;b&&3==g.Tx(a)?b.wm():this.SG(a)};
g.h.SG=function(a){try{if(a==this.Xc)a:{var b=g.Tx(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.Td&&!g.Ec(10)||g.Vd&&!g.Dc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yf&&!g.Xx(this.Xc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.Bf(3):this.o.Bf(2));J6(this);var e=this.Xc.getStatus();this.Am=e;var f=g.Xx(this.Xc);(this.Hf=200==e)?(4==b&&F6(this),this.D?(jEa(this,b,f),g.yf&&this.Hf&&3==b&&(this.Y.X(this.A,"tick",this.YU),this.A.start())):E6(this,f),this.Hf&&!this.ri&&(4==b?this.o.zq(this):
(this.Hf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Eh=3,D6(13)):(this.Eh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Xc&&g.Xx(this.Xc)}finally{}};
g.h.YU=function(){var a=g.Tx(this.Xc),b=g.Xx(this.Xc);this.Rn<b.length&&(J6(this),jEa(this,a,b),this.Hf&&4!=a&&B6(this))};
g.h.jU=function(a){I6((0,g.A)(this.iU,this,a),0)};
g.h.iU=function(a){this.ri||(J6(this),E6(this,a),B6(this))};
g.h.PE=function(a){I6((0,g.A)(this.hU,this,a),0)};
g.h.hU=function(a){this.ri||(F6(this),this.Hf=a,this.o.zq(this),this.o.Bf(4))};
g.h.cancel=function(){this.ri=!0;F6(this)};
g.h.yU=function(){this.ql=null;var a=(0,g.H)();0<=a-this.hy?(2!=this.Tj&&this.o.Bf(3),F6(this),this.Eh=2,D6(18),G6(this)):mEa(this,this.hy-a)};
g.h.getLastError=function(){return this.Eh};g.h=pEa.prototype;g.h.qu=null;g.h.Ge=null;g.h.Rq=!1;g.h.yB=null;g.h.Xo=null;g.h.xv=null;g.h.ru=null;g.h.af=null;g.h.Tg=-1;g.h.zm=null;g.h.Gl=null;g.h.connect=function(a){this.ru=a;a=L6(this.o,null,this.ru);D6(3);this.yB=(0,g.H)();var b=this.o.H;null!=b?(this.zm=b[0],(this.Gl=b[1])?(this.af=1,qEa(this)):(this.af=2,N6(this))):(d6(a,"MODE","init"),this.Ge=new z6(this,void 0,void 0,void 0),this.Ge.Ji=this.qu,A6(this.Ge,a,!1,null,!0),this.af=0)};
g.h.YJ=function(a){if(a)this.af=2,N6(this);else{D6(4);var b=this.o;b.Uf=b.rh.Tg;U6(b,9)}a&&this.Bf(2)};
g.h.Lt=function(a){return this.o.Lt(a)};
g.h.abort=function(){this.Ge&&(this.Ge.cancel(),this.Ge=null);this.Tg=-1};
g.h.xB=function(){return!1};
g.h.IE=function(a,b){this.Tg=a.Am;if(0==this.af)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Uf=this.Tg;U6(c,2);return}this.zm=c[0];this.Gl=c[1]}else c=this.o,c.Uf=this.Tg,U6(c,2);else if(2==this.af)if(this.Rq)D6(7),this.xv=(0,g.H)();else if("11111"==b){if(D6(6),this.Rq=!0,this.Xo=(0,g.H)(),c=this.Xo-this.yB,!g.Td||g.Ec(10)||500>c)this.Tg=200,this.Ge.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.Xo=this.xv=(0,g.H)(),this.Rq=!1};
g.h.zq=function(){this.Tg=this.Ge.Am;if(this.Ge.Hf)0==this.af?this.Gl?(this.af=1,qEa(this)):(this.af=2,N6(this)):2==this.af&&((!g.Td||g.Ec(10)?!this.Rq:200>this.xv-this.Xo)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.af?D6(9):2==this.af&&D6(10);var a=this.o;a.Uf=this.Tg;U6(a,2)}};
g.h.In=function(){return this.o.In()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Bf=function(a){this.o.Bf(a)};g.h=O6.prototype;g.h.Wl=null;g.h.ie=null;g.h.zc=null;g.h.pu=null;g.h.Zo=null;g.h.Qz=null;g.h.qp=null;g.h.nn=0;g.h.WP=0;g.h.Dd=null;g.h.xh=null;g.h.Fg=null;g.h.yi=null;g.h.rh=null;g.h.Nr=null;g.h.nk=-1;g.h.oC=-1;g.h.Uf=-1;g.h.Kj=0;g.h.Cj=0;g.h.wi=8;var V6=new g.Yf;g.B(sEa,g.wf);g.B(tEa,g.wf);g.B(uEa,g.wf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.pu=b;this.Wl=c||{};d&&g.za(e)&&(this.Wl.OSID=d,this.Wl.OAID=e);this.F?(I6((0,g.A)(this.jA,this,a),100),yEa(this)):this.jA(a)};
g.h.jA=function(a){this.rh=new pEa(this);this.rh.qu=null;this.rh.A=this.D;this.rh.connect(a)};
g.h.xB=function(){return 0==this.o};
g.h.OE=function(a){this.xh=null;BEa(this,a)};
g.h.NE=function(){this.Fg=null;this.zc=new z6(this,this.B,"rpc",this.G);this.zc.Ji=null;this.zc.tu=0;var a=this.Qz.clone();g.nn(a,"RID","rpc");g.nn(a,"SID",this.B);g.nn(a,"CI",this.Nr?"0":"1");g.nn(a,"AID",this.nk);P6(this,a);if(!g.Td||g.Ec(10))g.nn(a,"TYPE","xmlhttp"),A6(this.zc,a,!0,this.qp,!1);else{g.nn(a,"TYPE","html");var b=this.zc,c=!!this.qp;b.Tj=3;b.Dh=c6(a.clone());lEa(b,c)}};
g.h.IE=function(a,b){if(0!=this.o&&(this.zc==a||this.ie==a))if(this.Uf=a.Am,this.ie==a&&3==this.o)if(7<this.wi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Fg){if(this.zc)if(this.zc.Qk+3E3<this.ie.Qk)R6(this),this.zc.cancel(),this.zc=null;else break a;T6(this);D6(19)}}else this.oC=c[1],0<this.oC-this.nk&&37500>c[2]&&this.Nr&&0==this.Cj&&!this.yi&&(this.yi=I6((0,g.A)(this.AQ,this),6E3));else U6(this,11)}else b!=XFa.fZ.o&&U6(this,11);else if(this.zc==a&&
R6(this),!g.E(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.nk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.qp=e[2],e=e[3],null!=e?this.wi=e:this.wi=6,this.o=3,this.Dd&&this.Dd.dA(),this.Qz=L6(this,this.In()?this.qp:null,this.pu),CEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Dd&&this.Dd.cA(e),this.Cj=0)}}};
g.h.AQ=function(){null!=this.yi&&(this.yi=null,this.zc.cancel(),this.zc=null,T6(this),D6(20))};
g.h.zq=function(a){if(this.zc==a){R6(this);this.zc=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.Uf=a.Am;if(0!=this.o)if(a.Hf)1==b?(b=(0,g.H)()-a.Qk,V6.dispatchEvent(new tEa(V6,a.hj?a.hj.length:0,b,this.Kj)),Q6(this),this.C.length=0):CEa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.ie||this.xh||1==this.o||2<=this.Kj?d=!1:(this.xh=I6((0,g.A)(this.OE,this,a),DEa(this,this.Kj)),this.Kj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.vK=function(a){if(!g.Va(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.WV=function(a){a?D6(2):(D6(1),EEa(this,8))};
g.h.Lt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Nx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Dd&&this.Dd.isActive(this)};
g.h.Bf=function(a){V6.dispatchEvent(new uEa(V6,a))};
g.h.In=function(){return!(!g.Td||g.Ec(10))};
g.h=FEa.prototype;g.h.dA=function(){};
g.h.cA=function(){};
g.h.bA=function(){};
g.h.wt=function(){};
g.h.cB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.J);g.h=W6.prototype;g.h.ZT=function(){this.Ed=Math.min(3E5,2*this.Ed);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Ed+15E3*Math.random();g.Mu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ed=5E3};g.B(X6,FEa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.vk=function(a){return this.B.Ki(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Bb||(this.Bb=!0,g.uf(this.B),IEa(this),g.uf(this.A),this.A=null)};
g.h.la=function(){return this.Bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Dd=null);d.Dd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.nk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.qc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&zEa(this.o,c)};
g.h.dA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)zEa(this.o,a[b])}this.V("handlerOpened")};
g.h.bA=function(a){var b=2==a&&401==this.o.Uf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.wt=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.cB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.qc(a,this.D);return a};
g.h.cA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),xEa(this.o)):this.V("handlerMessage",new GEa(a[0],a[1]))};
g.h.zW=function(){this.A.isActive();var a=this.o,b=0;a.zc&&b++;a.ie&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var QEa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.V);g7.prototype.Ae=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.V);var YFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.UG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.DE(this.Ia),this.Ia=NaN)};
g.h.W=function(){this.stop();h7.ga.W.call(this)};
g.h.UG=function(){this.Ia=NaN;this.o=g.mF($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.BW,this),onError:(0,g.A)(this.AW,this),Id:(0,g.A)(this.DW,this)})};
g.h.BW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new g6(c))};
g.h.AW=function(a){this.o=null;a.status&&404==a.status?this.A>=YFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=YFa[this.A],this.Ia=g.BE((0,g.A)(this.UG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.DW=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.V("screenChange");!g.TH("yt-remote-lounge-token-expiration")&&UEa(this);g.DE(this.A);this.A=g.BE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);REa(this,a);k7(this,!1);this.V("screenChange");b(a);a.token||UEa(this)};
g.h.remove=function(a,b){var c=i7(this);TEa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Jr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.DE(this.A);j7.ga.W.call(this)};
g.h.kL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.jL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.V);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.TH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?o7(this):(this.C=(0,g.H)()+3E5,g.SH("yt-remote-fast-check-period",this.C),this.ax())};
g.h.isEmpty=function(){return g.ic(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Tb(this.o,function(b,d){return b&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.DE(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.W.call(this)};
g.h.ax=function(){g.DE(this.B);this.B=NaN;this.A&&this.A.abort();var a=XEa(this);if(g.Xb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.cc(a).join(",")},(0,g.A)(this.ET,this,a),(0,g.A)(this.DT,this))}else n7(this,{}),o7(this)};
g.h.ET=function(a,b){this.A=null;var c=g.cc(XEa(this));if(g.rb(c,g.cc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.sc("Changing Screen set during request."),this.ax()};
g.h.DT=function(a){this.sc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.sc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Jr=function(a,b,c,d){this.B.contains(a)?this.B.Jr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.Ae=function(a){return a?this.o:g.cb(this.o,(0,g.ge)(this.C,function(a){return!this.contains(a)},this))};
g.h.VG=function(){return(0,g.ge)(this.Ae(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.WG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.uf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.uf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.FW=function(a,b,c,d){g.mF($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new g6(d.screen||{});if(!e.name||aFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);aFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Id:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.uf(this.B);g.uf(this.A);p7.ga.W.call(this)};
g.h.xL=function(){bFa(this);this.V("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.V);g.h=s7.prototype;g.h.Aq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Fe=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){c7(this.R,a)};
g.h.YG=function(){return null};
g.h.rx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.rx("");s7.ga.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.qx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);dFa(this)};
g.h.qk=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Fe()},this),(0,g.A)(function(){this.Fe(Error("Failed to stop receiver app."))},this)):this.Fe(Error("Stopping cast device witout session."))};
g.h.rx=g.z;g.h.W=function(){this.info("disposeInternal");g.DE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.W.call(this)};
g.h.KU=function(a,b){if(!this.la())if(b){var c=g.Ix(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":cFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.nB=function(a,b,c,d){$Ea(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.BE((0,g.A)(this.nB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.YG=function(){return this.o};
g.h.GW=function(a){this.la()||a||(t7(this,"Cast session died."),this.Fe())};g.B(v7,s7);g.h=v7.prototype;g.h.qx=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.qk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.DE(this.F);this.C?this.C.stop((0,g.A)(this.Fe,this,null),(0,g.A)(this.Fe,this,"Failed to stop DIAL device.")):this.Fe()};
g.h.W=function(){this.o();this.o=g.z;g.DE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.W.call(this)};
g.h.JW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.z,this.Fe())};
g.h.Uu=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,fFa(this));a(b);eFa(this)}else this.G=(0,g.A)(function(){g.DE(this.F);this.G=g.z;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,fFa(this));a(b);eFa(this)},this),this.F=g.BE((0,g.A)(function(){this.G()},this),100)};
g.h.LM=function(a,b,c){$Ea(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Aq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Uu(b,c)},this),(0,g.A)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.Uu(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Fe()};
w7.prototype.qx=g.z;w7.prototype.qk=function(){g.DE(this.o);this.o=NaN;var a=m6(this.J.Ae(),this.A.label);a?this.Aq(a):this.Fe(Error("No such screen"))};
w7.prototype.W=function(){g.DE(this.o);this.o=NaN;w7.ga.W.call(this)};g.B(x7,g.V);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.KE,this),(0,g.A)(this.mT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.iR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),NEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.XG,this)),this.B=hFa(this),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.sc("Failed to set initial custom receivers: "+g.Og(a))},this)),this.V("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(a){this.sc("Failed to initialize API: "+g.Og(a));
b(!1)},this))};
g.h.EV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.Ae(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=gFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.z,(0,g.A)(function(a){this.sc("Failed to set initial custom receivers: "+g.Og(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.rx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.FV=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.qk(a):this.sc("Setting connection data without a session")};
g.h.IW=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.KE,this),(0,g.A)(this.IT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.XG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.$a(g.x("yt.mdx.remote.debug.handlers_")||[],KEa);g.uf(this.o);x7.ga.W.call(this)};
g.h.sc=function(a){c7("Controller",a)};
g.h.LE=function(a,b){this.o==a&&(b||A7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.iT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.iR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.LM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.Uu,b))};
g.h.KE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.Ae(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.uf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.LE,this,this.o)),this.o.qk(null));this.o.qx(a)}}};
g.h.HW=function(){return this.o?this.o.YG():null};
g.h.IT=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Og(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.mT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.V("yt-remote-cast2-availability-change",z7(this))}};
g.h.XG=function(){this.la()||(this.B=hFa(this),y7("Updating custom receivers: "+g.Og(this.B)),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.FV;x7.prototype.setConnectedScreenStatus=x7.prototype.EV;x7.prototype.stopSession=x7.prototype.IW;x7.prototype.getCastSession=x7.prototype.HW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Yf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!isNaN(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.La(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.WF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Og(b.style),g.qc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.WF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=U7(this);c.audioTrackId=b.Nb.id;W7(this,c)}else V7(this,g.La(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.za(b)&&(O7(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Og(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Gq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.Gq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.DA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.DA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){uFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.ry=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.aD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.dT=function(a,b){this.V(a,b)};
g.h.HQ=function(a){if(!a)this.tn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.tn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),vFa(this),this.V("remotePlayerChange")};
g.h.GQ=function(a){a?(vFa(this),this.V("remotePlayerChange")):this.tn(null)};
g.h.Hx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.TQ=function(){var a=rFa();a&&S7(this,a)};
g.h.sc=function(a){c7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.ob.listId=c);this.ob.videoId=d;this.ob.index=k||0;this.ob.state=3;O7(this.ob,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Og(l));this.o.connect({method:"setPlaylist",
params:g.Og(l)},a,UDa())}else a8("Connecting without params"),this.o.connect({},a,UDa());xFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.DE(this.J);this.J=NaN;g.DE(this.K);this.K=NaN;this.B=null;g.pG(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.ob=this.o=null};
g.h.aL=function(){this.F(2)};
g.h.LQ=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.BE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
YDa(HEa(this.o),this.aa)};
g.h.IQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.JQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.KQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.Og(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Ix(a.params.devices);this.A=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.Ra(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
AFa(this,a);break;case "loungeScreenDisconnected":g.ab(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
AFa(this,!1);break;case "remoteConnected":var b=new f6(g.Ix(a.params.device));g.Ra(this.A,function(a){return b?a.id==b.id:!1})||g.Ya(this.A,b);
break;case "remoteDisconnected":b=new f6(g.Ix(a.params.device));g.ab(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":CFa(this,a);break;case "nowPlaying":EFa(this,a);break;case "onStateChange":DFa(this,a);break;case "onAdStateChange":FFa(this,a);break;case "onVolumeChanged":GFa(this,a);break;case "onSubtitlesTrackChanged":BFa(this,a);break;case "nowAutoplaying":HFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":IFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.lV=function(){if(this.B){var a=this.B;this.B=null;this.ob.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.vk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&r6();IEa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.ob;this.B&&(a=this.ob.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.ob.videoId&&(this.B=b.videoId,g.DE(this.J),this.J=g.BE((0,g.A)(this.lV,this),5E3));var c=[];this.ob.listId==b.listId&&this.ob.videoId==b.videoId&&this.ob.index==b.index||c.push("remoteQueueChange");this.ob.playerState==b.playerState&&this.ob.volume==b.volume&&this.ob.muted==b.muted&&P7(this.ob)==P7(b)&&g.Og(this.ob.o)==g.Og(b.o)||c.push("remotePlayerChange");this.ob.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Ra(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ea=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ea;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.xa=function(){if(!isNaN(this.H())){var a=this.o.A;g.Nu(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);zFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.Ae=function(a){return this.md.$_gs(a)};
g.h.contains=function(a){return!!this.md.$_c(a)};
g.h.get=function(a){return this.md.$_g(a)};
g.h.start=function(){this.md.$_st()};
g.h.add=function(a,b,c){this.md.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.md.$_r(a,b,c)};
g.h.Jr=function(a,b,c,d){this.md.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.md.$_ubk(this.A[a]);this.A.length=0;this.md=null;g8.ga.W.call(this)};
g.h.EW=function(){this.V("screenChange")};
g.h.CS=function(){this.V("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.FW;p7.prototype.$_gsppc=p7.prototype.WG;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.Jr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.Ae;p7.prototype.$_gos=p7.prototype.VG;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.vk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.HE,this);this.o.unsubscribe("remotePlayerChange",this.wn,this);this.o.unsubscribe("remoteQueueChange",this.Bq,this);this.o.unsubscribe("autoplayUpNext",this.eE,this);this.o.unsubscribe("previousNextChange",this.EE,this);this.o.unsubscribe("nowAutoplaying",this.wE,this);this.o.unsubscribe("autoplayDismissed",this.dE,this);this.o=this.D=null};
g.h.fD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.wm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.FQ=function(a){this.L.VK(a)};
g.h.gW=function(a){this.fD("control_subtitles_set_track",g.ic(a)?null:a)};
g.h.lG=function(){var a=this.A.getOption("captions","track");g.ic(a)||C8(this,a)};
g.h.sE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.wn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.wn,this)}};
g.h.WR=function(){g.ic(this.G)||UFa(this,this.G);this.H=!1};
g.h.HE=function(a,b){this.F.stop();2==b&&this.jG()};
g.h.wn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.Uk(1);break;case 1082:case 1083:this.D.Uk(0);break;default:this.D.Uk(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.HQ(8));this.iG();break;case 1085:case 3:A8(this,new g.HQ(9));break;case 1083:case 0:A8(this,new g.HQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.HQ(4));break;case 2:A8(this,new g.HQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.HQ(64));break;case -1E3:A8(this,new g.HQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,UFa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.JG()}else TFa(this)};
g.h.EE=function(){this.A.V("mdxpreviousnextchange")};
g.h.Bq=function(){B8(this)||TFa(this)};
g.h.XJ=function(){this.o.DA()};
g.h.eE=function(a){a&&(a=g.mF("/watch_queue_ajax",{method:"GET",gd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.lU,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.lU=function(a,b){var c=new g.sP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.wE=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.dE=function(){this.A.V("mdxautoplaycanceled")};
g.h.zO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.JG=function(){if(B8(this)){var a=U7(this.o);this.B.Ma(this.T);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.T=this.B.O(this.A,"onVolumeChange",this.sE)}};
g.h.iG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.HQ(8));z8(this,P7(a));this.C.start()}};
g.h.jG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){WFa(this,a.state)};g.r(F8,g.ZW);F8.prototype.L=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.J=g.tb(a,this.F,this),g.$W(this,(0,g.I)(a,this.F)),a=this.B.getOption("remote","currentReceiver"),this.ng(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.hf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
F8.prototype.Gd=function(a){g.ZW.prototype.Gd.call(this,a);this.B.setOption("remote","currentReceiver",this.J[a]);this.C.Jb()};g.r(G8,g.kV);g.h=G8.prototype;g.h.create=function(){NFa(g.hN(g.Y(this.player)));this.D.push(g.IE("yt-remote-before-disconnect",this.BQ,this));this.D.push(g.IE("yt-remote-connection-change",this.nT,this));this.D.push(g.IE("yt-remote-receiver-availability-change",this.FE,this));this.D.push(g.IE("yt-remote-auto-connect",this.lT,this));this.D.push(g.IE("yt-remote-receiver-resumed",this.kT,this));this.FE()};
g.h.load=function(){this.player.cancelPlayback();g.kV.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=SFa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Ke(a);VFa(this,this.cn,this.cn);g.y0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.vf(this.C,this.o);this.o=this.C=null;g.kV.prototype.unload.call(this);g.y0(this.player.app,5)};
g.h.W=function(){g.JE(this.D);g.kV.prototype.W.call(this)};
g.h.Yh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.fD.apply(this.C,[a].concat(g.ea(c)))};
g.h.Uk=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.QK=function(){return this.loaded?this.C.suggestion:null};
g.h.Yf=function(){return this.o?U7(this.o).Yf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ke=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Pc():!a.isAdPlaying()&&this.player.Pc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+
N7(a):a.C}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Gq=function(){this.o&&this.o.Gq()};
g.h.BQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.nT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.uf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.FE=function(){this.F=[this.A].concat(PFa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.lT=function(){var a=s8();H8(this,a)};
g.h.kT=function(){this.B=s8()};
g.h.Kc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Hx=function(){this.o.Hx()};
g.h.uc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.RZ.remote=G8;})(_yt_player);
